---
# - name: create account
#   user:
#     name: '{{ username }}'
#     groups: 'sudo'
#     append: yes
#     password: $6$IMYQ5IgaoSz7ZJaR$1aTtxoglk8.dYTPKa/Wt2/YLz2qXv/z18jV.W1KtUEZH/TekA7ENvouMgufSNMqtSNCHNouhLCzk2313o4PZB1
#     shell: '/bin/bash'
#     home: '/home/{{ username }}'

- name: add proxy
  lineinfile:
    path: /etc/hosts
    line: 37.152.185.92 registry-1.docker.io download.docker.com k8s.gcr.io dl.k8s.io storage.googleapis.com apt.kubernetes.io packages.cloud.google.com gcr.io registry.gitlab.com gitlab.com charts.gitlab.io kubernetes-charts.storage.googleapis.com production.cloudflare.docker.com k8s.io docker.elastic.co docker-auth.elastic.co docker-auth.elastic.co d2iks1dkcwqcbx.cloudfront.net
    state: present

- name: add repo
  apt_repository:
    repo: deb http://artfiles.org/ubuntu.com/ focal-security multiverse
    state: present

- name: add repo
  apt_repository:
    repo: deb http://artfiles.org/ubuntu.com/ focal-security main restricted
    state: present

- name: add repo
  apt_repository:
    repo: deb http://artfiles.org/ubuntu.com/ focal-backports main restricted universe multiverse
    state: present

- name: "Update Repository cache"
  apt:
    update_cache: true
    cache_valid_time: 3600
    force_apt_get: true

# - name: install display manager
#   apt:
#     name: slim
#     state: latest

# - name: install desktop
#   apt:
#     name: ubuntu-desktop
#     state: latest

# - name: reboot
#   reboot:
#     reboot_timeout: 120

# - name: install docker packages
#   apt:
#     name: '{{ docker_required_packages }}'
#     state: latest
#     update_cache: yes
  
# - name: add docker's official GPG key
#   apt_key:
#     url: '{{ docker_gpg_url }}'
#     state: present
      
# - name: set up the stable repository
#   apt_repository:
#     repo: '{{ docker_repo }}'
#     state: present
#     update_cache: yes
  
# - name: update apt packages
#   apt:
#     update_cache: yes
  
# - name: install docker
#   apt:
#     name: '{{ docker_packges }}' 
#     state: latest 
#     update_cache: yes

# - name: install python docker module
#   pip:
#     name: docker

# - name: add user to docker group
#   user:
#     name: '{{ username }}'
#     groups: 'docker'
#     append: yes

# - name: install docker compose
#   get_url:
#     url: '{{ docker_compose_url }}'
#     dest: '/usr/local/bin/docker-compose'
#     mode: 'u+x,g+x,o+x'

# - name: add url
#   lineinfile:
#     path: /etc/hosts
#     line: 10.9.0.5 www.seed-server.com
#     state: present

# - name: install unzip
#   apt: 
#     name: unzip
#     state: latest

- name: unzip
  unarchive:
    src: 'files/Labsetup.zip'
    dest: '/home/{{ username }}/'
    owner: trainee
    mode: '777'
    copy: true

- name: installing webservice
  shell:
    cmd: docker-compose up
    chdir: '/home/{{ username }}/Labsetup'
  async: 120
  poll: 0
